# Generated by Django 3.1.2 on 2020-11-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prayer',
            options={'verbose_name': 'intenção', 'verbose_name_plural': 'intenções'},
        ),
        migrations.RemoveField(
            model_name='prayer',
            name='prayer',
        ),
        migrations.AddField(
            model_name='prayer',
            name='description',
            field=models.TextField(default=' ', verbose_name='intenção'),
            preserve_default=False,
        ),
    ]
