# Generated by Django 3.1.2 on 2020-11-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('prayer', models.TextField(verbose_name='preces')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='acesa em')),
            ],
        ),
    ]
